Adding social media links to the Footer
ProjectProtocol/project-protocol-nextjs pull request #62
Opened 2024-10-30 21:29 UTC by elchao96

## 🛠️ Changes

This adds social media links to the footer and sets them to wrap / be inline at mobile screens. 

## 🧪 Testing

<img width="856" alt="Screenshot 2024-10-30 at 1 59 52 PM" src="https://github.com/user-attachments/assets/8cfc8314-d9d8-489c-a952-8ec9e068063e">
<img width="394" alt="Screenshot 2024-10-30 at 2 00 12 PM" src="https://github.com/user-attachments/assets/8ad131ad-6ef8-42b1-9b91-7bc0c08f5115">

2024-10-31 20:20 UTC, eddie-m-m requested changes

2024-10-31 20:20 UTC, eddie-m-m commented on src/components/Footer.tsx
> +              <i className={`bi bi-${icon}`}></i>
I'm thinking this could be a bit bigger (as they seem to be on the ref design, I couldn't find any size recommendations or a figma link unfortunately), presumably for easier tap-ability on mobile.

2024-10-31 20:20 UTC, eddie-m-m commented on src/components/Footer.tsx
These are gonna be great. There are a couple comments I made relative to the reference design. 

Additionally, our custom mobile tabs are currently covering these icons on pages other than the landing page and rendering them inaccessible.


![Screenshot 2024-10-31 at 1 18 10 PM](https://github.com/user-attachments/assets/7cba8d41-5e16-42ea-a655-8896e5119d54)

2024-11-01 18:18 UTC, elchao96 commented on src/components/Footer.tsx
Updated! 
<img width="479" alt="Screenshot 2024-11-01 at 11 17 37 AM" src="https://github.com/user-attachments/assets/d857f4e2-6e08-403e-96f6-c0cedccdfb26">

2024-11-01 20:11 UTC, eddie-m-m commented on src/components/Footer.tsx
> +              <i className={`bi bi-${icon} h1`}></i>
```suggestion
              <i className={`bi bi-${icon}  fs-2`}></i>
```
For icons, the `font-size` class is standard for [sizing](https://icons.getbootstrap.com/#icon-font), so maybe something like this.

2024-11-01 20:15 UTC, eddie-m-m commented on src/components/Footer.tsx
Is that how it looked after scrolling to the bottom without further action? I can't seem to get that same view:


<img src="https://github.com/user-attachments/assets/ef0990b4-6194-4008-898b-3407115434e4" width="300"/>

2024-11-02 06:20 UTC, tasandberg commented on src/components/Footer.tsx
> +    <>
Fragments are only necessary if there's more than one top-level child, so this can be removed I think

2024-11-02 06:20 UTC, tasandberg commented on src/components/Footer.tsx
> +      <div className="bg-dark text-center mt-auto py-md-4 pt-4 pb-5">
I had the same UI bug as Eddy in his screenshot, where the icons on mobile are slightly under the bottom nav. I think you'll need to add something like `mb-3 mb-md-0` to add additional margin for small screens that goes away at the "medium" breakpoint.

2024-11-02 19:15 UTC, tasandberg approved these changes

2024-11-06 18:09 UTC, eddie-m-m approved these changes

2024-11-06 18:23 UTC, merged